THREE.OrbitControls=function(v,w){function x(){return Math.pow(.95,a.zoomSpeed)}function A(b){a.object.isPerspectiveCamera?y/=b:a.object.isOrthographicCamera?(a.object.zoom=Math.max(a.minZoom,Math.min(a.maxZoom,a.object.zoom*b)),a.object.updateProjectionMatrix(),z=!0):(console.warn("WARNING: OrbitControls.js encountered an unknown camera type - dolly/zoom disabled."),a.enableZoom=!1)}function H(b){a.object.isPerspectiveCamera?y*=b:a.object.isOrthographicCamera?(a.object.zoom=Math.max(a.minZoom,Math.min(a.maxZoom,
a.object.zoom/b)),a.object.updateProjectionMatrix(),z=!0):(console.warn("WARNING: OrbitControls.js encountered an unknown camera type - dolly/zoom disabled."),a.enableZoom=!1)}function B(a){g.set(a.clientX,a.clientY)}function C(a){h.set(a.clientX,a.clientY)}function I(a){1==a.touches.length?g.set(a.touches[0].pageX,a.touches[0].pageY):g.set(.5*(a.touches[0].pageX+a.touches[1].pageX),.5*(a.touches[0].pageY+a.touches[1].pageY))}function J(a){1==a.touches.length?h.set(a.touches[0].pageX,a.touches[0].pageY):
h.set(.5*(a.touches[0].pageX+a.touches[1].pageX),.5*(a.touches[0].pageY+a.touches[1].pageY))}function K(a){var b=a.touches[0].pageX-a.touches[1].pageX;a=a.touches[0].pageY-a.touches[1].pageY;m.set(0,Math.sqrt(b*b+a*a))}function M(b){1==b.touches.length?k.set(b.touches[0].pageX,b.touches[0].pageY):k.set(.5*(b.touches[0].pageX+b.touches[1].pageX),.5*(b.touches[0].pageY+b.touches[1].pageY));n.subVectors(k,g).multiplyScalar(a.rotateSpeed);b=a.domElement===document?a.domElement.body:a.domElement;f.theta-=
2*Math.PI*n.x/b.clientHeight;f.phi-=2*Math.PI*n.y/b.clientHeight;g.copy(k)}function N(b){1==b.touches.length?l.set(b.touches[0].pageX,b.touches[0].pageY):l.set(.5*(b.touches[0].pageX+b.touches[1].pageX),.5*(b.touches[0].pageY+b.touches[1].pageY));p.subVectors(l,h).multiplyScalar(a.panSpeed);q(p.x,p.y);h.copy(l)}function O(b){var c=b.touches[0].pageX-b.touches[1].pageX;b=b.touches[0].pageY-b.touches[1].pageY;r.set(0,Math.sqrt(c*c+b*b));u.set(0,Math.pow(r.y/m.y,a.zoomSpeed));A(u.y);m.copy(r)}function P(b){if(!1!==
a.enabled){b.preventDefault();a.domElement.focus?a.domElement.focus():window.focus();switch(b.button){case 0:switch(a.mouseButtons.LEFT){case THREE.MOUSE.ROTATE:if(b.ctrlKey||b.metaKey||b.shiftKey){if(!1===a.enablePan)return;C(b);d=c.PAN}else{if(!1===a.enableRotate)return;B(b);d=c.ROTATE}break;case THREE.MOUSE.PAN:if(b.ctrlKey||b.metaKey||b.shiftKey){if(!1===a.enableRotate)return;B(b);d=c.ROTATE}else{if(!1===a.enablePan)return;C(b);d=c.PAN}break;default:d=c.NONE}break;case 1:switch(a.mouseButtons.MIDDLE){case THREE.MOUSE.DOLLY:if(!1===
a.enableZoom)return;m.set(b.clientX,b.clientY);d=c.DOLLY;break;default:d=c.NONE}break;case 2:switch(a.mouseButtons.RIGHT){case THREE.MOUSE.ROTATE:if(!1===a.enableRotate)return;B(b);d=c.ROTATE;break;case THREE.MOUSE.PAN:if(!1===a.enablePan)return;C(b);d=c.PAN;break;default:d=c.NONE}}d!==c.NONE&&(document.addEventListener("mousemove",D,!1),document.addEventListener("mouseup",E,!1),a.dispatchEvent(F))}}function D(b){if(!1!==a.enabled)switch(b.preventDefault(),d){case c.ROTATE:if(!1===a.enableRotate)break;
k.set(b.clientX,b.clientY);n.subVectors(k,g).multiplyScalar(a.rotateSpeed);b=a.domElement===document?a.domElement.body:a.domElement;f.theta-=2*Math.PI*n.x/b.clientHeight;f.phi-=2*Math.PI*n.y/b.clientHeight;g.copy(k);a.update();break;case c.DOLLY:if(!1===a.enableZoom)break;r.set(b.clientX,b.clientY);u.subVectors(r,m);0<u.y?A(x()):0>u.y&&H(x());m.copy(r);a.update();break;case c.PAN:!1!==a.enablePan&&(l.set(b.clientX,b.clientY),p.subVectors(l,h).multiplyScalar(a.panSpeed),q(p.x,p.y),h.copy(l),a.update())}}
function E(b){!1!==a.enabled&&(document.removeEventListener("mousemove",D,!1),document.removeEventListener("mouseup",E,!1),a.dispatchEvent(G),d=c.NONE)}function Q(b){!1===a.enabled||!1===a.enableZoom||d!==c.NONE&&d!==c.ROTATE||(b.preventDefault(),b.stopPropagation(),a.dispatchEvent(F),0>b.deltaY?H(x()):0<b.deltaY&&A(x()),a.update(),a.dispatchEvent(G))}function R(b){if(!1!==a.enabled&&!1!==a.enableKeys&&!1!==a.enablePan){var c=!1;switch(b.keyCode){case a.keys.UP:q(0,a.keyPanSpeed);c=!0;break;case a.keys.BOTTOM:q(0,
-a.keyPanSpeed);c=!0;break;case a.keys.LEFT:q(a.keyPanSpeed,0);c=!0;break;case a.keys.RIGHT:q(-a.keyPanSpeed,0),c=!0}c&&(b.preventDefault(),a.update())}}function S(b){if(!1!==a.enabled){b.preventDefault();switch(b.touches.length){case 1:switch(a.touches.ONE){case THREE.TOUCH.ROTATE:if(!1===a.enableRotate)return;I(b);d=c.TOUCH_ROTATE;break;case THREE.TOUCH.PAN:if(!1===a.enablePan)return;J(b);d=c.TOUCH_PAN;break;default:d=c.NONE}break;case 2:switch(a.touches.TWO){case THREE.TOUCH.DOLLY_PAN:if(!1===
a.enableZoom&&!1===a.enablePan)return;a.enableZoom&&K(b);a.enablePan&&J(b);d=c.TOUCH_DOLLY_PAN;break;case THREE.TOUCH.DOLLY_ROTATE:if(!1===a.enableZoom&&!1===a.enableRotate)return;a.enableZoom&&K(b);a.enableRotate&&I(b);d=c.TOUCH_DOLLY_ROTATE;break;default:d=c.NONE}break;default:d=c.NONE}d!==c.NONE&&a.dispatchEvent(F)}}function T(b){if(!1!==a.enabled)switch(b.preventDefault(),b.stopPropagation(),d){case c.TOUCH_ROTATE:if(!1===a.enableRotate)break;M(b);a.update();break;case c.TOUCH_PAN:if(!1===a.enablePan)break;
N(b);a.update();break;case c.TOUCH_DOLLY_PAN:if(!1===a.enableZoom&&!1===a.enablePan)break;a.enableZoom&&O(b);a.enablePan&&N(b);a.update();break;case c.TOUCH_DOLLY_ROTATE:if(!1===a.enableZoom&&!1===a.enableRotate)break;a.enableZoom&&O(b);a.enableRotate&&M(b);a.update();break;default:d=c.NONE}}function U(b){!1!==a.enabled&&(a.dispatchEvent(G),d=c.NONE)}function V(b){!1!==a.enabled&&b.preventDefault()}this.object=v;this.domElement=void 0!==w?w:document;this.enabled=!0;this.target=new THREE.Vector3;this.minDistance=
0;this.maxDistance=Infinity;this.minZoom=0;this.maxZoom=Infinity;this.minPolarAngle=0;this.maxPolarAngle=Math.PI;this.minAzimuthAngle=-Infinity;this.maxAzimuthAngle=Infinity;this.enableDamping=!1;this.dampingFactor=.05;this.enableZoom=!0;this.zoomSpeed=1;this.enableRotate=!0;this.rotateSpeed=1;this.enablePan=!0;this.panSpeed=1;this.screenSpacePanning=!1;this.keyPanSpeed=7;this.autoRotate=!1;this.autoRotateSpeed=2;this.enableKeys=!0;this.keys={LEFT:37,UP:38,RIGHT:39,BOTTOM:40};this.mouseButtons={LEFT:THREE.MOUSE.ROTATE,
MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN};this.touches={ONE:THREE.TOUCH.ROTATE,TWO:THREE.TOUCH.DOLLY_PAN};this.target0=this.target.clone();this.position0=this.object.position.clone();this.zoom0=this.object.zoom;this.getPolarAngle=function(){return e.phi};this.getAzimuthalAngle=function(){return e.theta};this.saveState=function(){a.target0.copy(a.target);a.position0.copy(a.object.position);a.zoom0=a.object.zoom};this.reset=function(){a.target.copy(a.target0);a.object.position.copy(a.position0);
a.object.zoom=a.zoom0;a.object.updateProjectionMatrix();a.dispatchEvent(W);a.update();d=c.NONE};this.update=function(){var b=new THREE.Vector3,L=(new THREE.Quaternion).setFromUnitVectors(v.up,new THREE.Vector3(0,1,0)),aa=L.clone().inverse(),g=new THREE.Vector3,h=new THREE.Quaternion;return function(){var k=a.object.position;b.copy(k).sub(a.target);b.applyQuaternion(L);e.setFromVector3(b);a.autoRotate&&d===c.NONE&&(f.theta-=2*Math.PI/60/60*a.autoRotateSpeed);a.enableDamping?(e.theta+=f.theta*a.dampingFactor,
e.phi+=f.phi*a.dampingFactor):(e.theta+=f.theta,e.phi+=f.phi);e.theta=Math.max(a.minAzimuthAngle,Math.min(a.maxAzimuthAngle,e.theta));e.phi=Math.max(a.minPolarAngle,Math.min(a.maxPolarAngle,e.phi));e.makeSafe();e.radius*=y;e.radius=Math.max(a.minDistance,Math.min(a.maxDistance,e.radius));!0===a.enableDamping?a.target.addScaledVector(t,a.dampingFactor):a.target.add(t);b.setFromSpherical(e);b.applyQuaternion(aa);k.copy(a.target).add(b);a.object.lookAt(a.target);!0===a.enableDamping?(f.theta*=1-a.dampingFactor,
f.phi*=1-a.dampingFactor,t.multiplyScalar(1-a.dampingFactor)):(f.set(0,0,0),t.set(0,0,0));y=1;return z||g.distanceToSquared(a.object.position)>X||8*(1-h.dot(a.object.quaternion))>X?(a.dispatchEvent(W),g.copy(a.object.position),h.copy(a.object.quaternion),z=!1,!0):!1}}();this.dispose=function(){a.domElement.removeEventListener("contextmenu",V,!1);a.domElement.removeEventListener("mousedown",P,!1);a.domElement.removeEventListener("wheel",Q,!1);a.domElement.removeEventListener("touchstart",S,!1);a.domElement.removeEventListener("touchend",
U,!1);a.domElement.removeEventListener("touchmove",T,!1);document.removeEventListener("mousemove",D,!1);document.removeEventListener("mouseup",E,!1);window.removeEventListener("keydown",R,!1)};var a=this,W={type:"change"},F={type:"start"},G={type:"end"},c={NONE:-1,ROTATE:0,DOLLY:1,PAN:2,TOUCH_ROTATE:3,TOUCH_PAN:4,TOUCH_DOLLY_PAN:5,TOUCH_DOLLY_ROTATE:6},d=c.NONE,X=1E-6,e=new THREE.Spherical,f=new THREE.Spherical,y=1,t=new THREE.Vector3,z=!1,g=new THREE.Vector2,k=new THREE.Vector2,n=new THREE.Vector2,
h=new THREE.Vector2,l=new THREE.Vector2,p=new THREE.Vector2,m=new THREE.Vector2,r=new THREE.Vector2,u=new THREE.Vector2,Y=function(){var a=new THREE.Vector3;return function(b,c){a.setFromMatrixColumn(c,0);a.multiplyScalar(-b);t.add(a)}}(),Z=function(){var b=new THREE.Vector3;return function(c,d){!0===a.screenSpacePanning?b.setFromMatrixColumn(d,1):(b.setFromMatrixColumn(d,0),b.crossVectors(a.object.up,b));b.multiplyScalar(c);t.add(b)}}(),q=function(){var b=new THREE.Vector3;return function(c,d){var e=
a.domElement===document?a.domElement.body:a.domElement;if(a.object.isPerspectiveCamera){b.copy(a.object.position).sub(a.target);var f=b.length();f*=Math.tan(a.object.fov/2*Math.PI/180);Y(2*c*f/e.clientHeight,a.object.matrix);Z(2*d*f/e.clientHeight,a.object.matrix)}else a.object.isOrthographicCamera?(Y(c*(a.object.right-a.object.left)/a.object.zoom/e.clientWidth,a.object.matrix),Z(d*(a.object.top-a.object.bottom)/a.object.zoom/e.clientHeight,a.object.matrix)):(console.warn("WARNING: OrbitControls.js encountered an unknown camera type - pan disabled."),
a.enablePan=!1)}}();a.domElement.addEventListener("contextmenu",V,!1);a.domElement.addEventListener("mousedown",P,!1);a.domElement.addEventListener("wheel",Q,!1);a.domElement.addEventListener("touchstart",S,!1);a.domElement.addEventListener("touchend",U,!1);a.domElement.addEventListener("touchmove",T,!1);window.addEventListener("keydown",R,!1);this.update()};THREE.OrbitControls.prototype=Object.create(THREE.EventDispatcher.prototype);THREE.OrbitControls.prototype.constructor=THREE.OrbitControls;
THREE.MapControls=function(v,w){THREE.OrbitControls.call(this,v,w);this.mouseButtons.LEFT=THREE.MOUSE.PAN;this.mouseButtons.RIGHT=THREE.MOUSE.ROTATE;this.touches.ONE=THREE.TOUCH.PAN;this.touches.TWO=THREE.TOUCH.DOLLY_ROTATE};THREE.MapControls.prototype=Object.create(THREE.EventDispatcher.prototype);THREE.MapControls.prototype.constructor=THREE.MapControls;
var scene=new THREE.Scene,camera=new THREE.PerspectiveCamera(60,1,.1,1E3);camera.position.set(0,0,100);var renderer=new THREE.WebGLRenderer({antialias:!0}),canvas=renderer.domElement;document.body.appendChild(canvas);
for(var controls=new THREE.OrbitControls(camera,canvas),sideVals=[3,4,5,100],points=[],colors=[],c=new THREE.Color,sides=[],amount=11E3,i=0;i<amount;i++)points.push(new THREE.Vector3(THREE.Math.randFloatSpread(200),THREE.Math.randFloatSpread(200),THREE.Math.randFloatSpread(200))),c.set(16777215*Math.random()),colors.push(c.r,c.g,c.b),sides.push(sideVals[THREE.Math.randInt(0,3)]);var geom=(new THREE.BufferGeometry).setFromPoints(points);
geom.addAttribute("color",new THREE.BufferAttribute(new Float32Array(colors),3));geom.addAttribute("sides",new THREE.BufferAttribute(new Float32Array(sides),1));var mat=new THREE.PointsMaterial({vertexColors:THREE.VertexColors,alphaTest:.5,size:10});mat.extensions={derivatives:!0};
mat.onBeforeCompile=function(a){console.log(a.vertexShader);a.vertexShader="\nattribute float sides;\nvarying float vSides;\n"+a.vertexShader;a.vertexShader=a.vertexShader.replace("gl_PointSize = size;","gl_PointSize = size;\nvSides = sides;");a.fragmentShader="\nvarying float vSides;\n"+a.fragmentShader;a.fragmentShader=a.fragmentShader.replace("#include <clipping_planes_pars_fragment>","#include <clipping_planes_pars_fragment>\n\nfloat getShape(float thickness, float outer, vec2 uv){\n    uv *= 2.0;\n    float a = atan(uv.x,-uv.y) + 3.1415926;\n    float r = 3.1415926 * 2. / vSides;\n    float d = cos( floor( .5 + a / r ) * r - a ) * length( uv );\n    return smoothstep(thickness - fwidth(d), thickness + fwidth(d), d) - smoothstep(outer - fwidth(d), outer + fwidth(d), d);\n}\n");
a.fragmentShader=a.fragmentShader.replace("vec4 diffuseColor = vec4( diffuse, opacity );","\nvec3 base = vec3(0);\nfloat color = getShape(0.2, 0.4, gl_PointCoord - 0.5);\nvec4 diffuseColor = vec4( mix(base, diffuse, color), opacity );\nfloat shape = getShape(0.0, 0.5, gl_PointCoord - 0.5);\ndiffuseColor.a = shape;\n\n")};var collective=new THREE.Points(geom,mat);scene.add(collective);render();
function render(){resize(renderer)&&(camera.aspect=canvas.clientWidth/canvas.clientHeight,camera.updateProjectionMatrix());renderer.render(scene,camera);requestAnimationFrame(render)}function resize(a){var b=a.domElement,d=b.clientWidth,e=b.clientHeight;(b=b.width!==d||b.height!==e)&&a.setSize(d,e,!1);return b};
